title: My page
author: Olga Sapiga
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Hello! You are visiting my page now.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
